//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevToys.Extensions.CSharpCalculator {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CSharpCalculator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CSharpCalculator() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevToys.Extensions.CSharpCalculator.CSharpCalculator", typeof(CSharpCalculator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   This is a calculator using a C# script に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AccessibleName {
            get {
                return ResourceManager.GetString("AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy from header に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CopyHeader {
            get {
                return ResourceManager.GetString("CopyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   C# Script に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CSharpScript {
            get {
                return ResourceManager.GetString("CSharpScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Culture Info に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CultureInfo {
            get {
                return ResourceManager.GetString("CultureInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the CultureInfo to use when reading custom data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CultureInfoDescription {
            get {
                return ResourceManager.GetString("CultureInfoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Custom Type Definition に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CustomTypeDefinition {
            get {
                return ResourceManager.GetString("CustomTypeDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data Source に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DataSource {
            get {
                return ResourceManager.GetString("DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data Source Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DataSourceType {
            get {
                return ResourceManager.GetString("DataSourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the type of data to set in the &quot;Data Source&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DataSourceTypeDescription {
            get {
                return ResourceManager.GetString("DataSourceTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   C# Calculator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Has Header に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HasHeader {
            get {
                return ResourceManager.GetString("HasHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skip the first row of the data source as the header row. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HasHeaderDescription {
            get {
                return ResourceManager.GetString("HasHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   C# Calculator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LongDisplayTitle {
            get {
                return ResourceManager.GetString("LongDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calculators に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MyGroupAccessibleName {
            get {
                return ResourceManager.GetString("MyGroupAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calculators に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MyGroupDisplayTitle {
            get {
                return ResourceManager.GetString("MyGroupDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   C# Calculator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShortDisplayTitle {
            get {
                return ResourceManager.GetString("ShortDisplayTitle", resourceCulture);
            }
        }
    }
}
